### ISSUE TITLE
line number

### ISSUE THREAD

**Issue by yoandod** [MicrosoftDocs/visualstudio-docs.ko-kr#42]
I want the number of lines to be displayed on the left side of the screen (left side of line) in the visual study 2019 preview.
Please teach me the way.

visual studio 2019 preview에서 화면 왼쪽(라인 왼쪽)에 라인의 숫자를 보이게 하고 싶습니다.
방법을 알려주세요

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: db7f9ca8-40ce-6b6d-15df-bbb3b6829430
* Version Independent ID: 3dd10fed-b3d3-269c-623e-00031a81ed83
* Content: [빠른 시작: Visual Studio를 사용하여 Python 웹앱 만들기 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/ide/quickstart-python?view=vs-2017#feedback)
* Content Source: [docs/ide/quickstart-python.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/ide/quickstart-python.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
On the Tools menu, select Options, then expand Text Editor > Python. There's an option on that page for "Line Numbers."

**Comment by CeciAc** [comment]
Hello, @

I'm closing this issue since It was already addressed.
If you still need assistance, please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
