### ISSUE TITLE
I wanna acknowledge why different solution build result and project build result.

### ISSUE THREAD

**Issue by nicejmkim** [MicrosoftDocs/visualstudio-docs.ko-kr#66]
Hi, I'm college student in Korea.
I got a one of MESServer solution and dll file.
So I set this program and built this project one by one.
Result is not Error status. then I build MESServer solution, I got this error.
(LINK : fatal error LNK1123 : failure during conversion to COFF: file invaild or corrupt.)
I don't know why I got this error. I wanna answer and wanna know what is different solution build and project built result.
thank you.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [솔루션 및 프로젝트 - Visual Studio](https://docs.microsoft.com/ko-kr/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/blob/live/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by srvbpigh** [comment]
Hello, @nicejmkim
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nicejmkim 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4314

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
